### ISSUE TITLE
apiserver.ext does not exist

### ISSUE THREAD

**Issue by ghost** [cookeem/kubeadm-ha#1]
I am trying out v1.7. In the section to create certificates, I'm asked to edit this file: apiserver.ext

It does not exist either in current directory, or on the filesystem at all. Something is amiss.

**Comment by cookeem** [comment]
You must new apiserver.ext file by yourself

**Comment by ghost** [comment]
Okay so the apiserver.ext will contain the single line you have put in the step or should I reference this file from elsewhere?

I created `/etc/kubernetes/pki-local/apiserver.ext` containing:

`subjectAltName = DNS:vps138652.vps.ovh.eu,DNS:kubernetes,DNS:kubernetes.default,DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster.local, IP:10.96.0.1, IP:143.156.13.19, IP:178.11.321.678`

**Comment by cookeem** [comment]
Follow my steps, feel free to let me know it works?
