### ISSUE TITLE
在所有master上增加apiserver的apiserver-count设置后，kube-flannel-ds 启动失败

### ISSUE THREAD

**Issue by eanfs** [cookeem/kubeadm-ha#12]
在所有master上增加apiserver的apiserver-count设置
vi /etc/kubernetes/manifests/kube-apiserver.yaml
    - --apiserver-count=3

systemctl restart docker && systemctl restart kubelet

**Comment by cookeem** [comment]
有没有日志输出？dns的日志以及flannel的日志。

**Comment by cai11745** [comment]
我也有同样的现象，如果用官网文档在init的时候带上- --apiserver-count=3这个参数也是一样的现象。

问题在于kube-proxy异常
我后来又试了一遍添加这个=3的参数，三个master依次做，一个完成再下一个，不要一起，没出现问题

**Comment by YDD9** [comment]
官方文档说kubelet v1.9+的不用这个命令，用另外一条 endpoint-reconciler-type=lease
.
我的是kube-dns不能启动crash，统一了docker 和 kubelet的cgroupfs设置了 还是不行，有没有什么建议？ nginx来LB master api 的config有没有解释的文档链接 谢谢

**Comment by cookeem** [comment]
@YDD9 v1.9的确无需设置- --apiserver-count=3，已经删除这项描述，非常感谢。
