### ISSUE TITLE
初始化异常

### ISSUE THREAD

**Issue by ghost** [cookeem/kubeadm-ha#13]
初始化配置文件，podSubnet
networking:
  podSubnet: 10.244.0.0/16

但是初始化的日志显示如下内容：
Feb  7 08:23:46 master1 kubelet: I0207 08:23:46.268481    6924 kuberuntime_manager.go:918] updating runtime config through **cri with podcidr 10.244.0.0/24**
Feb  7 08:23:46 master1 kubelet: I0207 08:23:46.268679    6924 docker_service.go:343] docker cri received runtime config &RuntimeConfig{NetworkConfig:&**NetworkConfig{PodCidr:10.244.0.0/24,}**,}
Feb  7 08:23:46 master1 kubelet: I0207 08:23:46.268838    6924 kubelet_network.go:196] Setting Pod CIDR:  -> **10.244.0.0/24**

这是什么情况呢？之前我部署集群的时候发现flannel启动失败的问题，但是意外发现了如下的日志信息，着造成了flannel的networking字段与CIDR不一致，我猜测是flannel启动不成功的原因，之后修改flannel的networking进行匹配，成功启动。

**Comment by cookeem** [comment]
flannel的默认podsubnet就是10.244.0.0./16，calico的默认网络设置是192.168.0.0/16，所以要把calico的网络设置改为10.244.0.0./16，你如果改过这些设置，后边可能容易产生其他问题。
