### ISSUE TITLE
Kubelet service is down

### ISSUE THREAD

**Issue by coolpalani** [cookeem/kubeadm-ha#16]
When I was trying to bring up the server, it shows as down.

error: unable to load client CA file /etc/kubernetes/pki/ca.crt: open /etc/kubernetes/pki/ca.crt: no such file or directory

Is there any solutions start kubelet service

**Comment by cookeem** [comment]
Make sure you run kubeadm init first, it will create the CA and config files

**Comment by coolpalani** [comment]
Hi,

I ran kubeadm and started the kubelet service.
kubelet service has been started.

When I was execute ./create-config.sh shell script, the parameter it's not properly populated.

for example etcd/docker-compose.yaml file, if we are looking, calling --advertise-client-urls=http://K8SHA_IPLOCAL:2379,http://K8SHA_IPLOCAL:4001 


this K8SHA_IPLOCAL values can't pickup from shell script. if we are calling $K8SHA_IPLOCAL then It should takes values from export and run.

I even manually corrected and executed, but it's not working.
