### ISSUE TITLE
Calico and flanneld

### ISSUE THREAD

**Issue by rafaelsilvaa10** [cookeem/kubeadm-ha#17]
Hello,

I really liked the post, I'm implementing it and with some doubts.

Why did you use Calico and flanneld?

What is the function of each of them in the cluster?

I imagined they had the same function.

Thanks

**Comment by cookeem** [comment]
flannel is the level 2 network, it make the cluster nodes can connect each other. calico is the level 3 network, it make cluster can use network policy function.

**Comment by rafaelsilvaa10** [comment]
Ahh ok,  I'm thinking of using Weave instead of flanneld, because the weave have a great plugin ( weave scope) .  What do you think?

**Comment by cookeem** [comment]
I never try it, why not use it and tell me how your feelings?
