### ISSUE TITLE
楼主你好。关于flannel和calico

### ISSUE THREAD

**Issue by GoodJoey** [cookeem/kubeadm-ha#18]
官方文档里面，kubeadm init的时候 一般只需要一种网络模式就好了。
这里同时用了flannel和calico，是不是可以这么理解，flannel是用在master nodes之间的组网？ calico是cluster node之间的网络？ 
谢谢！

**Comment by cookeem** [comment]
之前的flannel+calico部署模式存在问题，已经更新为canal模式，请以master分支为准
