### ISSUE TITLE
nginx-lb.conf 

### ISSUE THREAD

**Issue by rockb1017** [cookeem/kubeadm-ha#19]
Hello,

I am really excited to find this post. 
One thing I find, I think this is error.

> /nginx-lb/docker-compose.yaml

    volumes:
    - /root/kube-yaml/nginx-lb/nginx-lb.conf:/etc/nginx/nginx.conf
I think "kube-yaml" directory name is hard coded. I have this file at 

> /root/kubeadm-ha/nginx-lb/nginx-lb.conf

**Comment by mxfj** [comment]
`
sed -i "s/root/opt/g" nginx-lb/docker-compose.yaml
`
`
sed -i "s/kube-yaml/kubeadm-ha/g" nginx-lb/docker-compose.yaml
`
like
`
version: '2'
services:
  etcd:
    image: nginx
    container_name: nginx-lb
    hostname: nginx-lb
    volumes:
    - /opt/kubeadm-ha/nginx-lb/nginx-lb.conf:/etc/nginx/nginx.conf
    ports:
    - 16443:16443
    restart: always
`

> 

docker-compose -f nginx-lb/docker-compose.yaml stop
docker-compose -f nginx-lb/docker-compose.yaml rm -f
docker-compose -f nginx-lb/docker-compose.yaml up -d

**Comment by cookeem** [comment]
@rockb1017 @mxfj get it, fixed
