### ISSUE TITLE
Q&A

### ISSUE THREAD

**Issue by rockb1017** [cookeem/kubeadm-ha#20]
Hello, 

I have a question. Though this is not related to Kube-HA, since you are the expert, I would like to ask.. 
Do we not need to set up Ingress Controller? 
what kind of features would Ingress Controller bring to this HA setup? 

Thanks,
Rock

**Comment by cookeem** [comment]
Here's the detail about ingress: 
https://kubernetes.io/docs/concepts/services-networking/ingress/
