### ISSUE TITLE
KUBECONFIG settings cannot be used in general user account

### ISSUE THREAD

**Issue by iamaugustin** [cookeem/kubeadm-ha#22]
If user runs in the general account, I suggest run the following instruction instead of "export KUBECONFIG=/etc/kubernetes/admin.conf".

sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config
export KUBECONFIG=$HOME/.kube/config

**Comment by cookeem** [comment]
Because this guide is run as root, just for my convenience. The method you show is recommended by official.
