### ISSUE TITLE
请问离线安装需要注意哪些事项呢

### ISSUE THREAD

**Issue by okjesse** [cookeem/kubeadm-ha#23]
谢谢，如题！

**Comment by cookeem** [comment]
1. docker镜像需要提前进行离线下载，可以使用docker save -o xxxx ; docker load -i xxxxx;
2. 注意yaml配置文件的imagePullPolicy，如果是Always需要改为IfNotPresent，同时需要注意镜像名字

**Comment by okjesse** [comment]
谢谢了！
