### ISSUE TITLE
calico网络插件疑问

### ISSUE THREAD

**Issue by ghost** [cookeem/kubeadm-ha#24]
记得你之前版本的部署文档中部署了两套网络，想请教以下，想更还cni网络插件的时候需要做那些清理工作，我目前想将flannel调整为calico，master01能正常启动，但是master02和03的calico node不能正常启动。
logs显示calico在master节点上建立的br-****都使用了172.18.0.0/16这个地址段，造成master02,03不能启动，请问有什么解决办法吗？

**Comment by cookeem** [comment]
之前的flannel+calico安装方式不正确，导致pod互访有问题，新文档的安装方式是canal，请更新

**Comment by iamaugustin** [comment]
現在改用Canal後，節點間的通訊埠是不是採用9099埠? 另外，kube-proxy會利用什麼埠進行節點間的通訊呢?

**Comment by Davidrjx** [comment]
@cookeem 您好，我在添加第一个worker node且更新bootstrap-kubelet和kubelet后，work上的cancl-**最后处于crashloopbackoff,请问可能是什么原因导致？
我的k8s version是1.9.0

**Comment by cookeem** [comment]
@Davidrjx 提供一下canal的pods日志？

**Comment by Davidrjx** [comment]
@cookeem , 谢谢你的回复！我现在已经改变方案，当时的logs不能重现！
