### ISSUE TITLE
couldn't parse external etcd version

### ISSUE THREAD

**Issue by rajesh-dcis** [cookeem/kubeadm-ha#27]
I did a kubeadm init --config=kubeadm-init.yaml and got the below error while initialising.

[ERROR ExternalEtcdVersion]: couldn't parse external etcd version "": Version string empty

**Comment by cookeem** [comment]
@rajesh-dcis can you show me your kubeadm-init.yaml file?

**Comment by epasham** [comment]
you get that error if kubeadm cant reach etcd during initialization. most likely the etcd endpoints given in the kubeadm-init.yaml  file are incorrect or ETCD is down.

**Comment by cookeem** [comment]
Since it support v1.11.x now, we should close it
