### ISSUE TITLE
Add configuring network interface for flannel

### ISSUE THREAD

**Issue by Mar4eli** [cookeem/kubeadm-ha#28]
According to official flannel [documentation](https://github.com/coreos/flannel/blob/master/Documentation/troubleshooting.md) there is a known issue with flannel and vagrant:

> Vagrant typically assigns two interfaces to all VMs. The first, for which all hosts are assigned the IP address 10.0.2.15, is for external traffic that gets NATed.
> 
> This may lead to problems with flannel. By default, flannel selects the first interface on a host. This leads to all hosts thinking they have the same public IP address. To prevent this issue, pass the --iface eth1 flag to flannel so that the second interface is chosen.

Can you please add network interface options for flannel in your cannal.yaml?

**Comment by cookeem** [comment]
There's two options related with network interface in `canal.yaml` file:

**Comment by cookeem** [comment]
@Mar4eli IP_AUTODETECTION_METHOD option related with network interface selection in `canal.yaml` file:
```
            - name: IP_AUTODETECTION_METHOD
              value: "can-reach=K8SHA_CALICO_REACHABLE_IP"
```
this will help you to select the network interface you expect not the first interface.

**Comment by Mar4eli** [comment]
Thanks, this helped!
