### ISSUE TITLE
ip address

### ISSUE THREAD

**Issue by Geekul** [cookeem/kubeadm-ha#32]
In hosts list, masters have ip address 192.168.20.20 ~ 22 and VIP have this ip 192.168.20.10 but in create-config.sh script you write this:
export K8SHA_VIP=192.168.60.79
# master01 ip address
export K8SHA_IP1=192.168.60.72
# master02 ip address
export K8SHA_IP2=192.168.60.77
# master03 ip address
export K8SHA_IP3=192.168.60.78
I think there's something wrong.

**Comment by cookeem** [comment]
Thx for your mention, I will fix it

**Comment by cookeem** [comment]
fixed
