### ISSUE TITLE
i have a problem "add etcd member to the cluster"

### ISSUE THREAD

**Issue by forkballpitch** [cookeem/kubeadm-ha#36]
hello~
i have a question about  "add etcd member to the cluster"

**my kubernetes version 1.12.1
and os is ubuntu 16.0.4**

i did 
**kubectl exec -n kube-system etcd-${CP0_HOSTNAME} -- etcdctl --ca-file /etc/kubernetes/pki/etcd/ca.crt --cert-file /etc/kubernetes/pki/tcd/peer.crt --key-file /etc/kubernetes/pki/etcd/peer.key --endpoints=https://${CP0_IP}:2379 member add ${CP1_HOSTNAME} https://${CP1_IP}:2380**

but i got 
**Unable to connect to the server: dial tcp 178.128.174.200:6443: i/o timeout**

this error.. firewalld was all down and i copied cert files already..

please help me thank you

**Comment by cookeem** [comment]
It seems your command is wrong, check this out:

/etc/kubernetes/pki/tcd/peer.crt

**Comment by cookeem** [comment]
Was that problem fixed?

**Comment by forkballpitch** [comment]
thank you for your kindness.
i misintepret the url.
i did https://VIP:30000

it did not work.
however,
"curl -k https://VIP:16443 <http://vip:16443/> " is worked between master
servers

thank you

2018년 10월 25일 (목) 오전 10:37, cookeem <notifications@github.com>님이 작성:

**Comment by cookeem** [comment]
show me the kube-dashboard status, run command below:

```
kubectl get pods -n kube-system
```

**Comment by forkballpitch** [comment]
my dashboard status is running like below



*root@k8s-master01:~# kubectl get pods -n kube-system*
*NAME                                    READY   STATUS    RESTARTS   AGE*
*calico-node-7gdv6                       2/2     Running   0          22h*
*calico-node-8f2rf                       2/2     Running   0          22h*
*calico-node-97ms9                       2/2     Running   0          22h*
*coredns-576cbf47c7-92hb5                1/1     Running   1          23h*
*coredns-576cbf47c7-jb54r                1/1     Running   1          23h*
*etcd-k8s-master01                       1/1     Running   3          23h*
*etcd-k8s-master02                       1/1     Running   3          22h*
*etcd-k8s-master03                       1/1     Running   1          22h*
*kube-apiserver-k8s-master01             1/1     Running   3          22h*
*kube-apiserver-k8s-master02             1/1     Running   1          22h*
*kube-apiserver-k8s-master03             1/1     Running   2          22h*
*kube-controller-manager-k8s-master01    1/1     Running   2          22h*
*kube-controller-manager-k8s-master02    1/1     Running   2          22h*
*kube-controller-manager-k8s-master03    1/1     Running   2          22h*
*kube-proxy-gvsf7                        1/1     Running   0          22h*
*kube-proxy-nczlh                        1/1     Running   0          22h*
*kube-proxy-pzq52                        1/1     Running   0          22h*
*kube-scheduler-k8s-master01             1/1     Running   3          23h*
*kube-scheduler-k8s-master02             1/1     Running   2          22h*
*kube-scheduler-k8s-master03             1/1     Running   1          22h*
*kubernetes-dashboard-7954d796d8-lqms7   1/1     Running   0          22h*




i set the vip like this.
*"ifconfig eth0:1 206.189.119.200  netmask 255.255.255.0  broadcast
206.189.119.1 up"*

in my master server i got this result like below
*root@k8s-master01:~# curl -k https://206.189.119.200:30000
<https://206.189.119.200:30000>*
* <!doctype html> <html ng-app="kubernetesDashboard"> <head> <meta
charset="utf-8"> <title ng-controller="kdTitle as $ctrl"
ng-bind="$ctrl.title()"></title> <link rel="icon" t*
*~~~~*

and in my local pc got this result

*rohyr@rohyr-Samsung-DeskTop-System:~$ curl -k
https://206.189.119.200:30000 <https://206.189.119.200:30000>*
*curl: (7) Failed to connect to 206.189.119.200 port 30000: *




2018년 10월 25일 (목) 오후 12:42, cookeem <notifications@github.com>님이 작성:

**Comment by cookeem** [comment]
Yes, the dashboard is normal, make sure the port not block by your cloud provider, you should check your cloud provider’s firewall settings

**Comment by forkballpitch** [comment]
thanks you~!
i'll check my cloud setting.
i'm using digital ocean cloud.
thank you very much!!! your kubernetes project is really helpful to me

2018년 10월 25일 (목) 오후 8:18, cookeem <notifications@github.com>님이 작성:

**Comment by cookeem** [comment]
You are welcome, I think this issue should be closed
