### ISSUE TITLE
i have a problem about nginx proxy

### ISSUE THREAD

**Issue by forkballpitch** [cookeem/kubeadm-ha#37]
hello~
it was very helpful your opinion.

my kubernetes version 1.12.1
and os is ubuntu 16.0.4

i did all kubernetes HA setting and
install dashboard 
so my url was http://VIP:30000

but it was not connected..
in my server curl -k http://VIP:16443 is worked
but my local did not worked. i registerd it in my hosts file ..

please help me thank you
thank you~!

**Comment by cookeem** [comment]
kubernetes-dashboard url is https://VIP:30000 not http.
