### ISSUE TITLE
dashboard无法连接

### ISSUE THREAD

**Issue by dotbalo** [cookeem/kubeadm-ha#39]
您好，我已经安装完所有组件如下：
[root@k8s-master01 ~]# kubectl get pods  -n kube-system
NAME                                    READY     STATUS    RESTARTS   AGE
calico-node-kwz9t                       2/2       Running   0          3h
calico-node-rj8p8                       2/2       Running   0          3h
calico-node-xfsg5                       2/2       Running   0          3h
coredns-777d78ff6f-4rcsb                1/1       Running   0          4h
coredns-777d78ff6f-7xqzx                1/1       Running   0          4h
etcd-k8s-master01                       1/1       Running   0          4h
etcd-k8s-master02                       1/1       Running   0          4h
etcd-k8s-master03                       1/1       Running   9          3h
heapster-5874d498f5-q2gzx               1/1       Running   0          13m
kube-apiserver-k8s-master01             1/1       Running   0          3h
kube-apiserver-k8s-master02             1/1       Running   0          3h
kube-apiserver-k8s-master03             1/1       Running   1          3h
kube-controller-manager-k8s-master01    1/1       Running   0          3h
kube-controller-manager-k8s-master02    1/1       Running   1          3h
kube-controller-manager-k8s-master03    1/1       Running   0          3h
kube-proxy-4cjhm                        1/1       Running   0          4h
kube-proxy-lkvjk                        1/1       Running   2          4h
kube-proxy-m7htq                        1/1       Running   0          4h
kube-scheduler-k8s-master01             1/1       Running   2          4h
kube-scheduler-k8s-master02             1/1       Running   0          4h
kube-scheduler-k8s-master03             1/1       Running   2          3h
kubernetes-dashboard-7954d796d8-2k4hx   1/1       Running   0          7m
metrics-server-55fcc5b88-r8v5j          1/1       Running   0          13m
monitoring-grafana-9b6b75b49-4zm6d      1/1       Running   0          45m
monitoring-influxdb-655cd78874-lmz5l    1/1       Running   0          45m

节点信息如下：
[root@k8s-master01 ~]# kubectl get nodes
NAME           STATUS    ROLES     AGE       VERSION
k8s-master01   Ready     master    4h        v1.11.1
k8s-master02   Ready     master    4h        v1.11.1
k8s-master03   Ready     master    4h        v1.11.1
通过curl访问dashboard的接口30000如下：
[root@k8s-master01 ~]# curl -k https://k8s-master-lb:30000
 <!doctype html> <html ng-app="kubernetesDashboard"> <head> <meta charset="utf-8"> <title ng-controller="kdTitle as $ctrl" ng-bind="$ctrl.title()"></title> <link rel="icon" type="image/png" href="assets/images/kubernetes-logo.png"> <meta name="viewport" content="width=device-width"> <link rel="stylesheet" href="static/vendor.93db0a0d.css"> <link rel="stylesheet" href="static/app.93e259f7.css"> </head> <body ng-controller="kdMain as $ctrl">  <kd-login layout="column" layout-fill ng-if="$ctrl.isLoginState()"> </kd-login> <kd-chrome layout="column" layout-fill ng-if="!$ctrl.isLoginState()"> </kd-chrome> <script src="static/vendor.bd425c26.js"></script> <script src="api/appConfig.json"></script> <script src="static/app.b5ad51ac.js"></script> </body> </html>

但是浏览器无法连接这个页面，请问您知道什么原因吗？
![image](https://user-images.githubusercontent.com/25141522/47782301-da977200-dd3a-11e8-9412-002b499d08be.png)

dashboard的pod日志如下:
[root@k8s-master01 ~]# kubectl logs kubernetes-dashboard-7954d796d8-2k4hx -n kube-system
2018/10/31 10:19:21 Starting overwatch
2018/10/31 10:19:21 Using in-cluster config to connect to apiserver
2018/10/31 10:19:21 Using service account token for csrf signing
2018/10/31 10:19:21 No request provided. Skipping authorization
2018/10/31 10:19:21 Successful initial request to the apiserver, version: v1.11.1
2018/10/31 10:19:21 Generating JWE encryption key
2018/10/31 10:19:21 New synchronizer has been registered: kubernetes-dashboard-key-holder-kube-system. Starting
2018/10/31 10:19:21 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2018/10/31 10:19:22 Initializing JWE encryption key from synchronized object
2018/10/31 10:19:22 Creating in-cluster Heapster client
2018/10/31 10:19:22 Auto-generating certificates
2018/10/31 10:19:22 Successfully created certificates
2018/10/31 10:19:22 Serving securely on HTTPS port: 8443
2018/10/31 10:19:22 Successful request to heapster
2018/10/31 10:23:50 http: TLS handshake error from 172.168.0.1:55803: tls: first record does not look like a TLS handshake
2018/10/31 10:25:04 http: TLS handshake error from 172.168.0.1:55814: tls: first record does not look like a TLS handshake
2018/10/31 10:28:34 http: TLS handshake error from 172.168.0.1:55888: tls: first record does not look like a TLS handshake

**Comment by dotbalo** [comment]
谷歌浏览器报错如下：
![image](https://user-images.githubusercontent.com/25141522/47782869-33b3d580-dd3c-11e8-96d3-6b43e9dfab0f.png)

**Comment by cookeem** [comment]
在chrome.exe后边增加参数 --test-type --ignore-certificate-errors
试一试？
你在自己电脑上curl dashboard地址可以访问不？

**Comment by dotbalo** [comment]
我使用火狐浏览器，添加安全例外才能访问，请问您的其他浏览器可以访问吗？
![image](https://user-images.githubusercontent.com/25141522/47783972-36fc9080-dd3f-11e8-8a54-0200116230dc.png)

或者有没有什么方式可以解决这个问题？

**Comment by cookeem** [comment]
我的是mac，chrome没有这个问题。firefox也可以安装证书的
