### ISSUE TITLE
can I use 127.0.0.1 or a domain when keepalived is not an option?

### ISSUE THREAD

**Issue by gensmusic** [cookeem/kubeadm-ha#4]
In my case, we cannot use keepalived. Therefor we have to use other ways.
I only think of two ways to get it done.
1. every node start a nginx to load three api servers. the node just join 127.0.0.1:8443 (8443 is the nginx port which load to real api servers.
2. use a domain such like k8s.mycompany.com.

I only test the first one, but I didn't work well.
I don't know if I missing something when configuration.

Can you give some advices on this ?
Any tips are appreciated.
Thank you very much.

**Comment by cookeem** [comment]
Actually I have no good idea to solve this problem, domain solution will cause single point of failure too. I heard some friends use pacemaker to make virtual ip, I think it's the same as keepalived.

**Comment by gensmusic** [comment]
thanks for replying. I find a way to make the keepalived work.
