### ISSUE TITLE
你好，按照你最新的文档安装后，工作节点calico-node不能完全就绪

### ISSUE THREAD

**Issue by liudonglin** [cookeem/kubeadm-ha#43]
![image](https://user-images.githubusercontent.com/16997773/48824452-54050c00-ed9f-11e8-9c3d-a5a562dcce6a.png)
![image](https://user-images.githubusercontent.com/16997773/48824503-75fe8e80-ed9f-11e8-83b3-c8194503fa80.png)

**Comment by liudonglin** [comment]
我是在阿里云上建立的一个内网负载均衡实例，将16443代理到三个master节点的6443端口，目前访问有问题
![image](https://user-images.githubusercontent.com/16997773/48831061-072a3100-edb1-11e8-9f64-aa42754ea0a6.png)

**Comment by liudonglin** [comment]
这个问题麻烦你删除了哈，是我自己配置的问题

**Comment by cookeem** [comment]
问题已关闭
