### ISSUE TITLE
一个小请求

### ISSUE THREAD

**Issue by Devying** [cookeem/kubeadm-ha#50]
楼主能否分享一下，基于k8s集群，利用Jenkins 做持续集成和构建，然后自动将代码上线到生产环境。

**Comment by cookeem** [comment]
这个是我现在在公司做的事情，Jenkins我们现在用jenkinsfile来编写流水线，Jenkins部署在k8s中，Jenkins再调用部署在k8s的docker in docker来远程执行流水线任务。思路大概是这样
