### ISSUE TITLE
太棒了，什么时候能出1.13版本呢

### ISSUE THREAD

**Issue by LemWong** [cookeem/kubeadm-ha#54]
有空的时候能更新一下1.13版本吗？不胜感激

**Comment by cookeem** [comment]
kubernetes的安装方式更新较大，v1.13版本高可用已经非常简单，你可以试一试官方的高可用安装。
https://kubernetes.io/docs/setup/independent/high-availability/

后续我再测试更新新版本，谢谢

**Comment by cookeem** [comment]
v1.14.0版本的高可用安装已经验证通过了，下周更新文档
