### ISSUE TITLE
k8s 1.14版本的部分文档错误

### ISSUE THREAD

**Issue by zeratullich** [cookeem/kubeadm-ha#57]
（1）kubeadm init --config=/root/kubeadm-config.yaml --experimental-upload-certs修改为：
kubeadm init --config=/root/kubeadm-ha/kubeadm-config.yaml --experimental-upload-certs
（2）配置文件kubeadm-config.yaml.tpl中的
apiServerCertSANs:
\- K8SHA_HOST1
\- K8SHA_HOST2
\- K8SHA_HOST3
.....
修改为：
apiServer:
   certSANs:
   \- K8SHA_HOST1
   \- K8SHA_HOST2
   \- K8SHA_HOST3
.....

否则报错：W0401 17:35:28.146593   18942 strict.go:54] error unmarshaling configuration schema.GroupVersionKind{Group:"kubeadm.k8s.io", Version:"v1beta1", Kind:"ClusterConfiguration"}: error unmarshaling JSON: while decoding JSON: json: unknown field "apiServerCertSANs"
其余未验证到问题。感谢作者能写的那么详细！鼓掌👏！加油！

**Comment by cookeem** [comment]
@zeratullich 非常感谢，我再确认一下一些细节问题

**Comment by cookeem** [comment]
我测试过使用那个配置是没有问题喔。
