### ISSUE TITLE
calico reachable ip address

### ISSUE THREAD

**Issue by zhangj3** [cookeem/kubeadm-ha#58]
大佬
这个calico reachable ip address是啥？可以自己随便自定义吗？还是说有特定的规则
# calico reachable ip address
export K8SHA_CALICO_REACHABLE_IP=172.20.10.1

**Comment by cookeem** [comment]
在多网卡情况下，需要指定一个ip地址，建议这个ip地址是你的hostip的gateway。

**Comment by zhangj3** [comment]
好的 谢谢！！
