### ISSUE TITLE
VIP 在其他master无法ping的通

### ISSUE THREAD

**Issue by zhangj3** [cookeem/kubeadm-ha#59]
用ip a 后发现VIP 在Master1上，master可以ping的通
在其他2个master却无法ping的通
所以其他master node都无法加入进来
有什么建议吗
谢谢

**Comment by cookeem** [comment]
应该是你的keepalived配置有问题，检查一下create-config.sh的配置项是否有设置错误？
看看keepalived的日志

**Comment by zhangj3** [comment]
谢谢你的及时回复，我忘了说我的坏境，master instances 都运行在redhat openstack上的Ubuntu，之前我也忽略了这一点。
3台master，在关掉任意一台后，ip a 能看到VIP跑到了其他master节点,就是其他backup的master无法ping通VIP。
在跟同事讨论外加谷歌之后发现是openstack网络组件Neutron的锅，目前正在尝试解决
https://access.redhat.com/solutions/3302731
https://medium.com/jexia/virtual-ip-with-openstack-neutron-dd9378a48bdf

PS 我也遇到了这个issue里的报错 https://github.com/cookeem/kubeadm-ha/issues/57   更改代码之后解决问题了
