### ISSUE TITLE
求助:Master集群都ok, work节点无法访问keepalived的VIP

### ISSUE THREAD

**Issue by yhtsnda** [cookeem/kubeadm-ha#60]
因为work节点无法访问keepalived的VIP，导致worknode无法加入到kube集群
有没有碰到这个问题，大概什么原因？
<img width="1068" alt="屏幕快照 2019-04-09 下午3 50 08" src="https://user-images.githubusercontent.com/1248897/55782589-341c7d80-5adf-11e9-930d-ac556f6e2d50.png">

**Comment by cookeem** [comment]
请认真检查你的create-config.sh中的配置，特别是以下几项配置：

**Comment by cookeem** [comment]
```bash
# master01 network interface name
export K8SHA_NETINF1=enp0s3

# master02 network interface name
export K8SHA_NETINF2=enp0s3

# master03 network interface name
export K8SHA_NETINF3=enp0s3

# keepalived auth_pass config
export K8SHA_KEEPALIVED_AUTH=412f7dc3bfed32194d1600c483e10ad1d
```
